FROM cica

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y install \
    python3-bottle
COPY web.py web.py
COPY entrypoint-web.sh /usr/local/bin/entrypoint-web.sh

ENTRYPOINT entrypoint-web.sh
